### ISSUE TITLE
Splash Image Not Showing on First Launch

### ISSUE THREAD

**Issue by AbnerBaluyut** [SimformSolutionsPvtLtd/splash_master#64]
Hi, I'm experiencing an issue with this splash_master configuration on Flutter.

After installing the app for the first time, the splash screen loads without showing the image logo.
However, the logo appears correctly on subsequent app launches (after closing and reopening).

Any idea how to fix or work around this? thanks in advance!

**Comment by AbnerBaluyut** [comment]
here’s the current configuration I’m using in splash_master:

```
splash_master:
  color: "#FFFFFF"
  image: "assets/png/logo.png"

  ios_content_mode: "center"
  android_gravity: "center"

  android_12_and_above:
    color: "#FFFFFF"
    image: "assets/png/logo.png"
```


The image shows correctly after the app is reopened, but on first launch after install, the splash screen loads without the logo. It’s just a blank white screen.

Let me know if there’s anything wrong with this setup or if the image needs to be in a native res/drawable folder for Android to display it correctly on cold start.

Thanks again!
